{{- if .Values.volumeSnapshotClass.create -}}
---
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: {{ .Values.volumeSnapshotClass.name | default "mgxcsi-snapshotclass" }}
  {{- if .Values.volumeSnapshotClass.isDefault }}
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
  {{- end }}
driver: {{ .Values.driverName }}
deletionPolicy: {{ .Values.volumeSnapshotClass.deletionPolicy | default "Delete" }}
parameters:
  {{- if .Values.volumeSnapshotClass.config }}
  config: {{ .Values.volumeSnapshotClass.config }}
  {{- end }}
  {{- if .Values.volumeSnapshotClass.labels }}
  labels: {{ .Values.volumeSnapshotClass.labels }}
  {{- end }}
  {{- if .Values.volumeSnapshotClass.incremental }}
  incremental: "{{ .Values.volumeSnapshotClass.incremental }}"
  {{- end }}
  {{- if .Values.volumeSnapshotClass.storageClass }}
  storage_class: "{{ .Values.volumeSnapshotClass.storageClass }}"
  {{- end }}
  {{- if .Values.volumeSnapshotClass.transfers }}
  transfers: "{{ .Values.volumeSnapshotClass.transfers }}"
  {{- end }}
  {{- if .Values.volumeSnapshotClass.checkers }}
  checkers: "{{ .Values.volumeSnapshotClass.checkers }}"
  {{- end }}
  {{- if ne (toString .Values.volumeSnapshotClass.maxIncrements) "<nil>" }}
  max_increments: "{{ .Values.volumeSnapshotClass.maxIncrements }}"
  {{- end }}
{{- end -}}
