---
apiVersion: v1
kind: Pod
metadata:
  name: mgxcsi-test-multi
  labels:
    app: mgxcsi-pvc
spec:
  containers:
  - name: alpine
    image: alpine:3
    imagePullPolicy: "IfNotPresent"
    command: ["sleep", "365d"]
    volumeMounts:
    - mountPath: "/mgxvol1"
      name: mgx-volume1
    - mountPath: "/mgxvol2"
      name: mgx-volume2
    - mountPath: "/mgxvol3"
      name: mgx-volume3
  volumes:
  - name: mgx-volume1
    persistentVolumeClaim:
      claimName: mgxcsi-pvc-1
  - name: mgx-volume2
    persistentVolumeClaim:
      claimName: mgxcsi-pvc-200
  - name: mgx-volume3
    persistentVolumeClaim:
      claimName: mgxcsi-pvc-500
